services:
  app:
    image: app
    build:
      context: PortugalAi
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    networks:
      - backend
    depends_on:
      - api
  api:
    image: api
    build:
      context: contextapi
      dockerfile: Dockerfile
    networks:
      - backend
networks:
  backend: {}
