services:
  app:
    image: app
    build:
      context: PortugalAi
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    networks:
      - back-tier
    depends_on:
      - api
  api:
    image: api
    build:
      context: contextapi
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    networks:
      - back-tier
networks:
  backend: {}
