# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./PortugalAi
        
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build
      run: dotnet build PortugalAi.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal PortugalAi.sln
